capstone/django/api/urls.py
from django.urls import path
from rest_framework.routers import DefaultRouter

from . import views

router = DefaultRouter()
router.register('users', views.PostSleepSet, basename='users')
router.register('sleeps', views.SleepAPIView, basename='sleeps')
router.register('quotes', views.QuoteViewSet)
router.register('moods', views.MoodViewSet)

urlpatterns = router.urls + [
    # path('', views.SleepAPIView.as_view()),
]

capstone/django/sleep_app/urls.py
from django.urls import path
from . import views

app_name = 'sleep_app'

urlpatterns = [
    path('', views.home_template, name='home'),
    path('account/', views.post_sleep_record, name='post_sleep_record'),
]

capstone/django/sleep_dues/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/v1/', include('api.urls')),
    path('users/', include('django.contrib.auth.urls')),
    path('users/', include('users.urls')),
    path('', include('sleep_app.urls'), name='home'),
]

capstone/django/users/urls.py
from django.urls import path
from rest_framework.routers import DefaultRouter

from . import views
from .views import SignUpView

router = DefaultRouter()
router.register('users', views.UserViewSet, basename='users')

urlpatterns = [
    path('signup/', SignUpView.as_view(), name='signup'),
    path('currentuser/', views.CurrentUserView.as_view()),
]

capstone/django/api/models.py
from django.db import models

# Create your models here.

class Mood(models.Model):
    name = models.CharField(max_length=255)
    def __str__(self):
        return str(self.name)

class Quote(models.Model):
    text = models.TextField()
    source = models.CharField(max_length=200, null=True)
    mood = models.ForeignKey(Mood, on_delete=models.CASCADE)
    def __str__(self):
        return str(self.source)

capstone/django/sleep_app/models.py
from django.db import models
from users.models import CustomUser

# Create your models here.

class Sleep(models.Model):
    user_id = models.ForeignKey(CustomUser, related_name="sleeps", on_delete=models.CASCADE)
    sleep_hours = models.IntegerField()
    date = models.DateField()

    def __str__(self):
        return str(self.user_id)

capstone/django/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class CustomUser(AbstractUser):
    MALE = True
    FEMALE = False
    GENDER_CHOICES = [
        (MALE, 'Male'),
        (FEMALE, 'Female'),
    ]
    username = models.CharField(max_length=50, unique=True)
    user_first_name = models.CharField(max_length=50)
    user_last_name = models.CharField(max_length=50)
    email = models.EmailField(max_length=254)
    user_age = models.IntegerField(default=None, blank=True, null=True)
    user_sex = models.BooleanField(choices=GENDER_CHOICES, null=True)

    def __str__(self):
        return self.username

    def delete(self):
        self.delete()
# Create your models here.

capstone/django/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import CustomUser

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = ('username', 'user_first_name', 'user_last_name', 'email', 'user_age', 'user_sex')

class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = CustomUser
        fields = ('username', 'user_first_name', 'user_last_name', 'email', 'user_age', 'user_sex')

capstone/django/api/views.py
from django.shortcuts import render
from rest_framework import generics, viewsets

from users.models import CustomUser
from sleep_app.models import Sleep
from .models import Quote, Mood
from .serializers import UserSerializer, SleepSerializer, QuoteSerializer, MoodSerializer

# Create your views here.

class SleepAPIView(viewsets.ModelViewSet):
    queryset = Sleep.objects.all()
    serializer_class = SleepSerializer

class PostSleepSet(viewsets.ModelViewSet):
    queryset = CustomUser.objects.all()
    serializer_class = UserSerializer

class QuoteViewSet(viewsets.ModelViewSet):
    queryset = Quote.objects.all()
    serializer_class = QuoteSerializer

class MoodViewSet(viewsets.ModelViewSet):
    queryset = Mood.objects.all()
    serializer_class = MoodSerializer

capstone/django/sleep_app/views.py
from django.shortcuts import render
from django.views.generic import ListView
from .models import Sleep


# Create your views here.

class SleepListView(ListView):
    model = Sleep
    template_name = 'home.html'

def home_template(request):
    return render(request, 'home.html')

def post_sleep_record(request):
    return render(request, 'user_update.html')

capstone/django/users/views.py
from django.shortcuts import render, get_object_or_404, HttpResponseRedirect
from rest_framework import generics, viewsets, permissions
from django.views.generic.edit import CreateView
from django.views.generic import DetailView
from django.urls import reverse_lazy, reverse
from users.models import CustomUser
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404, render, redirect
from django.http import HttpResponse
from django.contrib.auth.models import User

from api.serializers import UserSerializer
from api.permissions import IsAuthorOrReadOnly
from .forms import CustomUserCreationForm

# Create your views here.

class SignUpView(CreateView):
    form_class = CustomUserCreationForm
    template_name = 'registration/signup.html'
    success_url = reverse_lazy('login')

class CurrentUserView(generics.RetrieveUpdateAPIView):
    serializer_class = UserSerializer
    def get_object(self):
        return self.request.user

class UserViewSet(viewsets.ReadOnlyModelViewSet):
    queryset = CustomUser
    serializer_class = UserSerializer
    permission_classes = [permissions.IsAuthenticatedOrReadOnly]

capstone/django/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Sleep Dues</title>
        
        {% block styles %}
        <link rel="stylesheet" href="{% static 'styles.css' %}">
        <link rel="stylesheet" href="{{ STATIC_URL }}css/header.css">
        <link rel="stylesheet" href="{{ STATIC_URL }}css/sidebar.css">
        <link rel="stylesheet" href="{{ STATIC_URL }}css/main.css">
        <link rel="stylesheet" href="{{ STATIC_URL }}css/footer.css">
        {% endblock styles %}
            
    </head>
    <body>
        <header>
            {% include 'header.html' %}
            <h1>Sleep Dues Header</h1> 
            <nav id="navBar">
                <a href="#" class="headerList">Home</a>
                <a href="#" class="headerList">How it works</a>
                <a href="#" class="headerList">About Us</a>
                <a href="#" class="headerList">Contact Us</a>
                <a href="#" class="headerList">Get Started</a>
            </nav>
        </header>
        <nav>
            {% include 'sidebar.html' %}
        </nav> 
        <main>
            {% include 'user_mainview.html' %}
        </main>
        <div class="columns">
            <div id="left" class="sidebar">
                <h1>Sleep Dues</h1>
                <nav class="nav">
                    <div class="nav__list">
                    </div>
                </nav>
            </div>
            <div id="right" class="mainBody">
                {% block user_home %}
                <p>HI</p>
                {% endblock user_home %}   
            </div>
        </div>
    </body>
</html>

capstone/django/templates/graph.html
<canvas id="myChart"></canvas>

capstone/django/templates/header.html
{% load static %}


<link rel="stylesheet" href="{% static 'header.css' %}">

    
{% if request.path == '/' %}
    <p class="header-icon"></p> 
{% else %} 
    <a class="header-icon" href="{% url 'sleep_app:home' %}">
        <img id="logo" src="https://cdn.cp.adobe.io/content/2/dcx/1a952aba-9e35-495e-98da-2831d6d9587f/rendition/preview.jpg/version/1/format/jpg/dimension/width/size/1200" alt="Home icon"/> 
    </a>
{% endif %}

capstone/django/templates/home copy.html
<!DOCTYPE html>
<html lang="en">
    {% load static %}
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sleep Dues</title>
</head>
<body>
    {% csrf_token %}
    <div id="app">

        <h1>Welcome [[ currentUser.username ]] to Sleep Dues</h1>

        {% if user.is_authenticated %}

            <a href="{% url 'logout' %}">Logout</a>
        {% else %}
            <a href="{% url 'signup' %}">Signup</a>
            <a href="{% url 'login' %}">Login</a>
        {% endif %}

        {% comment %} <h1>Welcome to Sleep Dues</h1> {% endcomment %}
        <div v-for="user in userData">
            <p>[[ user ]]</p>
            <p>[[ user.user_age ]]</p>
        </div>
        
        <div>
            <input type="text" placeholder="username" v-model="userSleepData.username">
            <input type="text" placeholder="first name" v-model="userSleepData.user_first_name">
            <input type="text" placeholder="last name" v-model="userSleepData.user_last_name">
            <input type="number" placeholder="age" v-model="userSleepData.user_age">
            {% comment %} <input type="number" placeholder="Hours of Sleep" v-model="userSleepData.sleep_hours">
            <input type="date" v-model="userSleepData.date"> {% endcomment %}
            <button @click="uploadSleepData">Upload Sleep Data</button>
        </div>
        {% comment %} <p>[[ message ]]</p> {% endcomment %}
    </div>


 <!-- Import Ajax -->
 <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>

 <!-- Import Vue.js -->
 <script src="https://unpkg.com/vue@3/dist/vue.global.js"></script>

 <!-- Import file.js -->
 <script src="{% static '/app.js' %}"></script>

 <!-- Mount App -->
 <script> const mountApp = app.mount('#app') </script>

</body>
</html>

capstone/django/templates/home.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sleep Dues</title>
    <link rel="stylesheet" href="{% static 'styles.css' %}">
    

        
</head>
<body>
    {% csrf_token %}
    <div id="app">
        <header>
            {% include 'header.html' %}
        </header>
        <div class="columns">
            <div id="left" class="sidebar">
                {% if  request.path == '/'  and not user.is_authenticated %}
                    <p class="header-icon"></p>
                {% else %} 
                    <a class="header-icon" href="{% url 'sleep_app:home' %}">
                        <img id="logo" src="https://cdn.cp.adobe.io/content/2/dcx/cdfaf2a5-7900-4a8f-9c3c-bb6e2dc74b05/rendition/preview.jpg/version/0/format/jpg/dimension/width/size/1200" alt="Home icon"/> 
                    </a>
                    <br>
                {% endif %}

                <nav class="nav">
                    <div class="nav__list">
                        {% if user.is_authenticated %}
                            <p id=sidebarIcon></p>
                            <p>Welcome [[ currentUser.username ]]</p>
                            <a href="{% url 'sleep_app:post_sleep_record' %}" class="nav__list-item">Sleep Log</a>
                            <a href="{% url 'logout' %}" class="nav__list-item">Log out</a>
                        {% else %} 
                            <a href="{% url 'signup' %}" class="nav__list-item">Register</a>
                            <a href="{% url 'login' %}" class="nav__list-item">Log In</a>
                        {% endif %}
                    </div>
                </nav>
            </div>
            <div id="right" class="mainBody">
                {% block login %}
                {% block register %}
                {% block user_update %}
                    {% if user.is_authenticated %}
                    {% include 'user.html' %}
                    {% else %}
                    {% include 'nonuser.html' %}
                    {% endif %}
                {% endblock user_update %}
                {% endblock register %}
                {% endblock login %}
            </div>
        </div>
    </div>


 <!-- Import Ajax -->
 <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>

 <!-- Import Vue.js -->
 <script src="https://unpkg.com/vue@3/dist/vue.global.js"></script>

 <!-- Import file.js -->
 <script src="{% static '/app.js' %}"></script>
 <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>


 <!-- Mount App -->
 <script> const mountApp = app.mount('#app') </script>

</body>
</html>

capstone/django/templates/nonuser.html
{% csrf_token %}

<div id=sloganContainer>
    <img id="slogan" src="https://cdn.cp.adobe.io/content/2/dcx/52d57b73-4a84-4421-adc1-d305349193ff/rendition/preview.jpg/version/3/format/jpg/dimension/width/size/1200" />
</div>
    <div class="row">
    <div class="bodyColumns">
        <img class="memojis" src="https://media1.giphy.com/media/5mBCYxJ7PHidsZVRkf/giphy.gif" alt="Computer man" style="width:150px;height:150px;" /> 
        <img class="memojis" src="https://media2.giphy.com/media/wE19ivfoD5fTHXemFu/giphy.gif" alt="Computer man" style="width:150px;height:150px;" /> 
    </div>
    <div class="textColumn">
        <div class="sloganText">
            <br>
            <p>Learn more about how sleep can affect your [[ word ]].</p>
            <br>
            <p>SIGN UP FOR SLEEP DUES NOW!</p>
        </div>
        <br>
        <a href="{% url 'signup' %}" id="startButton">START HERE</a>
    </div>
    <div class="bodyColumns">
        <img class="memojis" src="https://media4.giphy.com/media/e34oyThs8eSqTlKus3/giphy.gif" alt="Computer man" style="width:150px;height:150px;" /> 
        <img class="memojis" src="https://media0.giphy.com/media/7Vlz6G2Cqtvz3Z7KWB/giphy.gif" alt="Computer man" style="width:150px;height:150px;" /> 

    </div>
  </div>

capstone/django/templates/user.html
{% csrf_token %}

<div id="sleepHealth">
    <p>Sleep Health Data</p>
</div>
<div id="loadingSpinner" style="display: block;">
    <div class="spinner"></div>
</div>

<div id=mainElement style="display: none;">
    <div v-if="sleepLog.length >= 3">
        {% include 'graph.html' %}
        <div id="underGraph">
            <img v-bind:src="userMemoji" class="memojis" alt="Computer man" style="width:300px;height:300px;" />
            <div id="quoteCard">
                <br><br>
                <p id="record">[[ moodText ]]</p>
                <br>
                <p id="record">[[ moodSource ]]</p>
            </div>
        </div>
    </div>

    <div id="subText" v-else>
        <br>
        <p>Sorry, we need some more sleep data to work with.</p>
        <p>Catch those ZzZ and check back in when you have logged at least 3 nights.</p>
        <img id="subTextLogo" src="https://cdn.cp.adobe.io/content/2/dcx/e1ab8475-b9a8-4742-b9e5-e6df13c3aaad/rendition/preview.jpg/version/1/format/jpg/dimension/width/size/1200" style="width:300px;height:300px;" />
    </div>

    
</div>

capstone/django/templates/user_home.html
{% extends base.html %}

{% csrf_token %}
<div id="app">
    {% if user.is_authenticated %}
    {% include 'user.html' %}
    {% else %}
    {% include 'nonuser.html' %}
    {% endif %}

    {% comment %} <h1>Welcome [[ currentUser.username ]] to Sleep Dues</h1>
    {% include 'graph.html' %}
    <img class="memojis" src="https://media4.giphy.com/media/dQgl5JyyjHxABAqrWR/giphy.gif?cid=790b7611448d11fec6b4df088e42fd52657ecf0462e0d1de&rid=giphy.gif&ct=g" alt="Computer man" style="width:300px;height:300px;" /> {% endcomment %}
</div>


<!-- Import Ajax -->
<script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>

<!-- Import Vue.js -->
<script src="https://unpkg.com/vue@3/dist/vue.global.js"></script>

<!-- Import file.js -->
<script src="{% static '/app.js' %}"></script>
<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>


<!-- Mount App -->
<script> const mountApp = app.mount('#app') </script>

capstone/django/templates/user_update.html
{% extends 'home.html' %}

{% block user_update %}


<div class="register-form"> 
    <h1>Post Sleep Record</h1>
    <form >
        {% csrf_token %}
        <label for="id_date">Date:</label><br>
        <input type="date" name="date" id="id_date" v-model="userSleepData.date"><br>
        <label for="id_sleep_hours">Sleep Hours:</label><br>
        <input type="number" name="sleep_hours" id="id_sleep_hours" v-model="userSleepData.sleep_hours"><br><br>
        <button @click="uploadSleepData" class=fancyButton>Upload</button>
    </form>
</div>
<br>

<!-- Use a container to center the table -->
<div class="table-container">
    <table>
        <thead>
            <tr>
                <th>Date</th>
                <th>Sleep Hours</th>
                <th>Delete Record</th>
            </tr>
        </thead>
        <tbody>
            <tr v-for="sleep in sleepLog" :key="sleep.id">
                <td>[[ sleep.date ]]</td>
                <td>[[ sleep.sleep_hours ]]</td>
                <td>
                    <button @click="deleteSleepRecord(sleep.id)">Delete</button>
                </td>
            </tr>
        </tbody>
    </table>
</div>




{% endblock %}